// ============================================================
// TabibPro — Seed Data — Pharmacopée Algérienne (ANPP)
// Médicaments courants disponibles sur le marché algérien
// ============================================================

export const MEDICAMENTS_DZ_SEED = [
  // ---- Antalgiques / Antipyrétiques ----
  {
    nomCommercial: 'Paracétamol Saidal 500mg',
    nomCommercialAr: 'باراسيتامول سايدال 500 مغ',
    dci: 'Paracétamol',
    forme: 'comprime',
    dosageUnitaire: '500',
    uniteDosage: 'mg',
    codeAtc: 'N02BE01',
    fabricant: 'Saidal',
    paysOrigine: 'Algérie',
    estFabriqueLocalement: true,
    estGenerique: true,
    prixPublicAlgerie: 150,
    tauxRemboursement: 80,
    listeClassification: 'EN_VENTE_LIBRE',
    disponibleMarcheDz: true,
    voieAdministration: 'orale',
  },
  {
    nomCommercial: 'Paracétamol Saidal 1g',
    nomCommercialAr: 'باراسيتامول سايدال 1 غ',
    dci: 'Paracétamol',
    forme: 'comprime',
    dosageUnitaire: '1000',
    uniteDosage: 'mg',
    codeAtc: 'N02BE01',
    fabricant: 'Saidal',
    paysOrigine: 'Algérie',
    estFabriqueLocalement: true,
    estGenerique: true,
    prixPublicAlgerie: 250,
    tauxRemboursement: 80,
    listeClassification: 'EN_VENTE_LIBRE',
    disponibleMarcheDz: true,
    voieAdministration: 'orale',
  },
  {
    nomCommercial: 'Efferalgan 500mg',
    nomCommercialAr: 'إيفرلجان 500 مغ',
    dci: 'Paracétamol',
    forme: 'comprime_effervescent',
    dosageUnitaire: '500',
    uniteDosage: 'mg',
    codeAtc: 'N02BE01',
    fabricant: 'UPSA (Bristol-Myers Squibb)',
    paysOrigine: 'France',
    estFabriqueLocalement: false,
    estGenerique: false,
    prixPublicAlgerie: 380,
    tauxRemboursement: 80,
    listeClassification: 'EN_VENTE_LIBRE',
    disponibleMarcheDz: true,
    voieAdministration: 'orale',
  },
  // ---- Antibiotiques ----
  {
    nomCommercial: 'Amoxicilline Saidal 500mg',
    nomCommercialAr: 'أموكسيسيلين سايدال 500 مغ',
    dci: 'Amoxicilline',
    forme: 'gelule',
    dosageUnitaire: '500',
    uniteDosage: 'mg',
    codeAtc: 'J01CA04',
    fabricant: 'Saidal',
    paysOrigine: 'Algérie',
    estFabriqueLocalement: true,
    estGenerique: true,
    prixPublicAlgerie: 350,
    tauxRemboursement: 80,
    listeClassification: 'LISTE_I',
    disponibleMarcheDz: true,
    voieAdministration: 'orale',
  },
  {
    nomCommercial: 'Amoxicilline Biopharm 1g',
    nomCommercialAr: 'أموكسيسيلين بيوفارم 1 غ',
    dci: 'Amoxicilline',
    forme: 'comprime',
    dosageUnitaire: '1000',
    uniteDosage: 'mg',
    codeAtc: 'J01CA04',
    fabricant: 'Biopharm',
    paysOrigine: 'Algérie',
    estFabriqueLocalement: true,
    estGenerique: true,
    prixPublicAlgerie: 580,
    tauxRemboursement: 80,
    listeClassification: 'LISTE_I',
    disponibleMarcheDz: true,
    voieAdministration: 'orale',
  },
  {
    nomCommercial: 'Ciprofloxacine LPA 500mg',
    nomCommercialAr: 'سيبروفلوكساسين لبا 500 مغ',
    dci: 'Ciprofloxacine',
    forme: 'comprime',
    dosageUnitaire: '500',
    uniteDosage: 'mg',
    codeAtc: 'J01MA02',
    fabricant: 'LPA',
    paysOrigine: 'Algérie',
    estFabriqueLocalement: true,
    estGenerique: true,
    prixPublicAlgerie: 650,
    tauxRemboursement: 80,
    listeClassification: 'LISTE_I',
    disponibleMarcheDz: true,
    voieAdministration: 'orale',
  },
  // ---- Anti-inflammatoires ----
  {
    nomCommercial: 'Ibuprofène Saidal 400mg',
    nomCommercialAr: 'إيبوبروفين سايدال 400 مغ',
    dci: 'Ibuprofène',
    forme: 'comprime',
    dosageUnitaire: '400',
    uniteDosage: 'mg',
    codeAtc: 'M01AE01',
    fabricant: 'Saidal',
    paysOrigine: 'Algérie',
    estFabriqueLocalement: true,
    estGenerique: true,
    prixPublicAlgerie: 280,
    tauxRemboursement: 80,
    listeClassification: 'LISTE_II',
    disponibleMarcheDz: true,
    voieAdministration: 'orale',
  },
  // ---- Antihypertenseurs ----
  {
    nomCommercial: 'Amlodipine El Kendi 5mg',
    nomCommercialAr: 'أملوديبين الكندي 5 مغ',
    dci: 'Amlodipine',
    forme: 'comprime',
    dosageUnitaire: '5',
    uniteDosage: 'mg',
    codeAtc: 'C08CA01',
    fabricant: 'El Kendi',
    paysOrigine: 'Algérie',
    estFabriqueLocalement: true,
    estGenerique: true,
    prixPublicAlgerie: 420,
    tauxRemboursement: 100,
    listeClassification: 'LISTE_II',
    disponibleMarcheDz: true,
    voieAdministration: 'orale',
  },
  {
    nomCommercial: 'Ramipril Biopharm 5mg',
    nomCommercialAr: 'راميبريل بيوفارم 5 مغ',
    dci: 'Ramipril',
    forme: 'gelule',
    dosageUnitaire: '5',
    uniteDosage: 'mg',
    codeAtc: 'C09AA05',
    fabricant: 'Biopharm',
    paysOrigine: 'Algérie',
    estFabriqueLocalement: true,
    estGenerique: true,
    prixPublicAlgerie: 380,
    tauxRemboursement: 100,
    listeClassification: 'LISTE_II',
    disponibleMarcheDz: true,
    voieAdministration: 'orale',
  },
  // ---- Antidiabétiques ----
  {
    nomCommercial: 'Metformine Saidal 850mg',
    nomCommercialAr: 'ميتفورمين سايدال 850 مغ',
    dci: 'Metformine',
    forme: 'comprime',
    dosageUnitaire: '850',
    uniteDosage: 'mg',
    codeAtc: 'A10BA02',
    fabricant: 'Saidal',
    paysOrigine: 'Algérie',
    estFabriqueLocalement: true,
    estGenerique: true,
    prixPublicAlgerie: 320,
    tauxRemboursement: 100,
    listeClassification: 'LISTE_II',
    disponibleMarcheDz: true,
    voieAdministration: 'orale',
  },
  {
    nomCommercial: 'Insuline Humaine NPH Saidal',
    nomCommercialAr: 'أنسولين بشري إن بي أتش سايدال',
    dci: 'Insuline humaine (isophane)',
    forme: 'injectable',
    dosageUnitaire: '100',
    uniteDosage: 'UI/mL',
    codeAtc: 'A10AC01',
    fabricant: 'Saidal',
    paysOrigine: 'Algérie',
    estFabriqueLocalement: true,
    estGenerique: false,
    prixPublicAlgerie: 850,
    tauxRemboursement: 100,
    listeClassification: 'LISTE_I',
    disponibleMarcheDz: true,
    voieAdministration: 'sous_cutanee',
  },
  // ---- Médicaments en rupture fréquente ----
  {
    nomCommercial: 'Furosémide 40mg',
    nomCommercialAr: 'فوروسيميد 40 مغ',
    dci: 'Furosémide',
    forme: 'comprime',
    dosageUnitaire: '40',
    uniteDosage: 'mg',
    codeAtc: 'C03CA01',
    fabricant: 'Importé',
    paysOrigine: 'Inde',
    estFabriqueLocalement: false,
    estGenerique: true,
    prixPublicAlgerie: 280,
    tauxRemboursement: 100,
    listeClassification: 'LISTE_II',
    disponibleMarcheDz: false, // Souvent en rupture
    voieAdministration: 'orale',
  },
  // ---- Antituberculeux (spécifique Algérie — forte prévalence TB) ----
  {
    nomCommercial: 'Isoniazide 150mg',
    nomCommercialAr: 'إيزونيازيد 150 مغ',
    dci: 'Isoniazide',
    forme: 'comprime',
    dosageUnitaire: '150',
    uniteDosage: 'mg',
    codeAtc: 'J04AC01',
    fabricant: 'Saidal',
    paysOrigine: 'Algérie',
    estFabriqueLocalement: true,
    estGenerique: false,
    prixPublicAlgerie: 0, // Gratuit programme national
    tauxRemboursement: 100,
    listeClassification: 'LISTE_I',
    disponibleMarcheDz: true,
    voieAdministration: 'orale',
  },
  {
    nomCommercial: 'Rifampicine 300mg',
    nomCommercialAr: 'ريفامبيسين 300 مغ',
    dci: 'Rifampicine',
    forme: 'gelule',
    dosageUnitaire: '300',
    uniteDosage: 'mg',
    codeAtc: 'J04AB02',
    fabricant: 'Saidal',
    paysOrigine: 'Algérie',
    estFabriqueLocalement: true,
    estGenerique: false,
    prixPublicAlgerie: 0, // Gratuit programme national TB
    tauxRemboursement: 100,
    listeClassification: 'LISTE_I',
    disponibleMarcheDz: true,
    voieAdministration: 'orale',
  },
];
