// ============================================================
// TabibPro — Seed Data — 58 Wilayas d'Algérie
// ============================================================

export const WILAYAS_DZ = [
  { code: '01', nomFr: 'Adrar', nomAr: 'أدرار', chefLieu: 'Adrar' },
  { code: '02', nomFr: 'Chlef', nomAr: 'الشلف', chefLieu: 'Chlef' },
  { code: '03', nomFr: 'Laghouat', nomAr: 'الأغواط', chefLieu: 'Laghouat' },
  { code: '04', nomFr: 'Oum El Bouaghi', nomAr: 'أم البواقي', chefLieu: 'Oum El Bouaghi' },
  { code: '05', nomFr: 'Batna', nomAr: 'باتنة', chefLieu: 'Batna' },
  { code: '06', nomFr: 'Béjaïa', nomAr: 'بجاية', chefLieu: 'Béjaïa' },
  { code: '07', nomFr: 'Biskra', nomAr: 'بسكرة', chefLieu: 'Biskra' },
  { code: '08', nomFr: 'Béchar', nomAr: 'بشار', chefLieu: 'Béchar' },
  { code: '09', nomFr: 'Blida', nomAr: 'البليدة', chefLieu: 'Blida' },
  { code: '10', nomFr: 'Bouira', nomAr: 'البويرة', chefLieu: 'Bouira' },
  { code: '11', nomFr: 'Tamanrasset', nomAr: 'تمنراست', chefLieu: 'Tamanrasset' },
  { code: '12', nomFr: 'Tébessa', nomAr: 'تبسة', chefLieu: 'Tébessa' },
  { code: '13', nomFr: 'Tlemcen', nomAr: 'تلمسان', chefLieu: 'Tlemcen' },
  { code: '14', nomFr: 'Tiaret', nomAr: 'تيارت', chefLieu: 'Tiaret' },
  { code: '15', nomFr: 'Tizi Ouzou', nomAr: 'تيزي وزو', nomBer: 'ⵜⵉⵣⵉ ⵡⵣⵣⵓ', chefLieu: 'Tizi Ouzou' },
  { code: '16', nomFr: 'Alger', nomAr: 'الجزائر', chefLieu: 'Alger' },
  { code: '17', nomFr: 'Djelfa', nomAr: 'الجلفة', chefLieu: 'Djelfa' },
  { code: '18', nomFr: 'Jijel', nomAr: 'جيجل', chefLieu: 'Jijel' },
  { code: '19', nomFr: 'Sétif', nomAr: 'سطيف', chefLieu: 'Sétif' },
  { code: '20', nomFr: 'Saïda', nomAr: 'سعيدة', chefLieu: 'Saïda' },
  { code: '21', nomFr: 'Skikda', nomAr: 'سكيكدة', chefLieu: 'Skikda' },
  { code: '22', nomFr: 'Sidi Bel Abbès', nomAr: 'سيدي بلعباس', chefLieu: 'Sidi Bel Abbès' },
  { code: '23', nomFr: 'Annaba', nomAr: 'عنابة', chefLieu: 'Annaba' },
  { code: '24', nomFr: 'Guelma', nomAr: 'قالمة', chefLieu: 'Guelma' },
  { code: '25', nomFr: 'Constantine', nomAr: 'قسنطينة', chefLieu: 'Constantine' },
  { code: '26', nomFr: 'Médéa', nomAr: 'المدية', chefLieu: 'Médéa' },
  { code: '27', nomFr: 'Mostaganem', nomAr: 'مستغانم', chefLieu: 'Mostaganem' },
  { code: '28', nomFr: "M'Sila", nomAr: 'المسيلة', chefLieu: "M'Sila" },
  { code: '29', nomFr: 'Mascara', nomAr: 'معسكر', chefLieu: 'Mascara' },
  { code: '30', nomFr: 'Ouargla', nomAr: 'ورقلة', chefLieu: 'Ouargla' },
  { code: '31', nomFr: 'Oran', nomAr: 'وهران', chefLieu: 'Oran' },
  { code: '32', nomFr: 'El Bayadh', nomAr: 'البيض', chefLieu: 'El Bayadh' },
  { code: '33', nomFr: 'Illizi', nomAr: 'إليزي', chefLieu: 'Illizi' },
  { code: '34', nomFr: 'Bordj Bou Arréridj', nomAr: 'برج بوعريريج', chefLieu: 'Bordj Bou Arréridj' },
  { code: '35', nomFr: 'Boumerdès', nomAr: 'بومرداس', chefLieu: 'Boumerdès' },
  { code: '36', nomFr: 'El Tarf', nomAr: 'الطارف', chefLieu: 'El Tarf' },
  { code: '37', nomFr: 'Tindouf', nomAr: 'تندوف', chefLieu: 'Tindouf' },
  { code: '38', nomFr: 'Tissemsilt', nomAr: 'تيسمسيلت', chefLieu: 'Tissemsilt' },
  { code: '39', nomFr: 'El Oued', nomAr: 'الوادي', chefLieu: 'El Oued' },
  { code: '40', nomFr: 'Khenchela', nomAr: 'خنشلة', chefLieu: 'Khenchela' },
  { code: '41', nomFr: 'Souk Ahras', nomAr: 'سوق أهراس', chefLieu: 'Souk Ahras' },
  { code: '42', nomFr: 'Tipaza', nomAr: 'تيبازة', chefLieu: 'Tipaza' },
  { code: '43', nomFr: 'Mila', nomAr: 'ميلة', chefLieu: 'Mila' },
  { code: '44', nomFr: 'Aïn Defla', nomAr: 'عين الدفلى', chefLieu: 'Aïn Defla' },
  { code: '45', nomFr: 'Naâma', nomAr: 'النعامة', chefLieu: 'Naâma' },
  { code: '46', nomFr: 'Aïn Témouchent', nomAr: 'عين تيموشنت', chefLieu: 'Aïn Témouchent' },
  { code: '47', nomFr: 'Ghardaïa', nomAr: 'غرداية', chefLieu: 'Ghardaïa' },
  { code: '48', nomFr: 'Relizane', nomAr: 'غليزان', chefLieu: 'Relizane' },
  { code: '49', nomFr: "Timimoun", nomAr: 'تيميمون', chefLieu: 'Timimoun' },
  { code: '50', nomFr: 'Bordj Badji Mokhtar', nomAr: 'برج باجي مختار', chefLieu: 'Bordj Badji Mokhtar' },
  { code: '51', nomFr: 'Ouled Djellal', nomAr: 'أولاد جلال', chefLieu: 'Ouled Djellal' },
  { code: '52', nomFr: 'Béni Abbès', nomAr: 'بني عباس', chefLieu: 'Béni Abbès' },
  { code: '53', nomFr: 'In Salah', nomAr: 'عين صالح', chefLieu: 'In Salah' },
  { code: '54', nomFr: 'In Guezzam', nomAr: 'عين قزام', chefLieu: 'In Guezzam' },
  { code: '55', nomFr: 'Touggourt', nomAr: 'تقرت', chefLieu: 'Touggourt' },
  { code: '56', nomFr: 'Djanet', nomAr: 'جانت', chefLieu: 'Djanet' },
  { code: '57', nomFr: "El M'Ghair", nomAr: 'المغير', chefLieu: "El M'Ghair" },
  { code: '58', nomFr: 'El Meniaa', nomAr: 'المنيعة', chefLieu: 'El Meniaa' },
];
